modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL=""
license="MIT License"

[[mods]]
modId="farmersdelightintegration"
version="1.16.5-1.0.1"
displayName="Farmer's Delight Integration"
# updateJSONURL=""
# displayURL=""
# logoFile="logo.png"
# logoBlur=false
credits="vectorwing"
authors="iku_tv"
description="Farmer's Delight mod integration."

[[dependencies.farmersdelightintegration]]
modId="forge"
mandatory=true
versionRange="[34,)"
ordering="NONE"
side="BOTH"

[[dependencies.farmersdelightintegration]]
modId="minecraft"
mandatory=true
versionRange="[1.16.3]"
ordering="NONE"
side="BOTH"

[[dependencies.farmersdelightintegration]]
modId = "farmersdelight"
mandatory = true
versionRange = "[1.16.3-0.3.2,)"
ordering = "AFTER"
side = "BOTH"